export const FETCH_PHOTOGRAPHY_REQUEST = "FETCH_PHOTOGRAPHY_REQUEST";
export const FETCH_PHOTOGRAPHY_SUCCESS = "FETCH_PHOTOGRAPHY_SUCCESS";
export const FETCH_PHOTOGRAPHY_FAILURE = "FETCH_PHOTOGRAPHY_FAILURE";
