export const FETCH_CATERING_REQUEST = 'FETCH_CATERING_REQUEST';
export const FETCH_CATERING_SUCCESS = 'FETCH_CATERING_SUCCESS';
export const FETCH_CATERING_FAILURE = 'FETCH_CATERING_FAILURE';
// gettingbookcateringservices

export const FETCH_VIEWCATERING_REQUEST = 'FETCH_VIEWCATERING_REQUEST';
export const FETCH_VIEWCATERING_SUCCESS = 'FETCH_VIEWCATERING_SUCCESS';
export const FETCH_VIEWCATERING_FAILURE = 'FETCH_VIEWCATERING_FAILURE';
export const SET_SELECTED_EMAIL = ' SET_SELECTED_EMAIL';
export const SET_SELECTED_DEALER = 'SET_SELECTED_DEALER';
export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';
