export const FETCH_VIEWSALOON_REQUEST = 'FETCH_VIEWSALOON_REQUEST';
export const FETCH_VIEWSALOON_SUCCESS = 'FETCH_VIEWSALOON_SUCCESS';
export const FETCH_VIEWSALOON_FAILURE = 'FETCH_VIEWSALOON_FAILURE';
