export const FETCH_SALOONORDER_REQUEST = 'FETCH_SALOONORDER_REQUEST';
export const FETCH_SALOONORDER_SUCCESS = 'FETCH_SALOONORDER_SUCCESS';
export const FETCH_SALOONORDER_FAILURE = 'FETCH_SALOONORDER_FAILURE';
