export const FETCH_VIEWCATERING_REQUEST = 'FETCH_VIEWCATERING_REQUEST';
export const FETCH_VIEWCATERING_SUCCESS = 'FETCH_VIEWCATERING_SUCCESS';
export const FETCH_VIEWCATERING_FAILURE = 'FETCH_VIEWCATERING_FAILURE';
