export const FETCH_BOOKSALOON_REQUEST = "FETCH_BOOKSALOON_REQUEST";
export const FETCH_BOOKSALOON_SUCCESS = "FETCH_BOOKSALOON_SUCCESS";
export const FETCH_BOOKSALOON_FAILURE = "FETCH_BOOKSALOON_FAILURE";
