export const FETCH_DELDEALERS_REQUEST = 'FETCH_DELDEALERS_REQUEST';
export const FETCH_DELDEALERS_SUCCESS = 'FETCH_DELDEALERS_SUCCESS';
export const FETCH_DELDEALERS_FAILURE = 'FETCH_DELDEALERS_FAILURE';
