export const FETCH_VIEWCARORDERSBOOKING_REQUEST =
  'FETCH_VIEWCARORDERSBOOKING_REQUEST';
export const FETCH_VIEWCARORDERSBOOKING_SUCCESS =
  'FETCH_VIEWCARORDERSBOOKING_SUCCESS';
export const FETCH_VIEWCARORDERSBOOKING_FAILURE =
  'FETCH_VIEWCARORDERSBOOKING_FAILURE';
