export const FETCH_CARRENT_REQUEST = 'FETCH_CARRENT_REQUEST';
export const FETCH_CARRENT_SUCCESS = 'FETCH_CARRENT_SUCCESS';
export const FETCH_CARRENT_FAILURE = 'FETCH_CARRENT_FAILURE';
export const SET_SELECTED_DEALER = 'SET_SELECTED_DEALER';
export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';
export const SET_SELECTED_EMAIL = 'SET_SELECTED_EMAIL';
