export const FETCH_SALOON_SERVICE_REQUEST = 'FETCH_SALOON_SERVICES_REQUEST';
export const FETCH_SALOON_SERVICE_SUCCESS = 'FETCH_SALOON_SERVICE_SUCCESS';
export const FETCH_SALOON_SERVICE_FAILURE = 'FETCH_SALOON_SERVICE_FAILURE';
