export const FETCH_SALOON_SERVICE_REQUEST = 'FETCH_SALOON_SERVICES_REQUEST';
export const FETCH_SALOON_SERVICE_SUCCESS = 'FETCH_SALOON_SERVICE_SUCCESS';
export const FETCH_SALOON_SERVICE_FAILURE = 'FETCH_SALOON_SERVICE_FAILURE';
export const SET_SELECTED_EMAIL = ' SET_SELECTED_EMAIL';
export const SET_SELECTED_DEALER = 'SET_SELECTED_DEALER';
export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';
