// post data
export const FETCH_GIVEORDERSTATUS_REQUEST = 'FETCH_GIVEORDERSTATUS_REQUEST';
export const FETCH_GIVEORDERSTATUS_SUCCESS = 'FETCH_GIVEORDERSTATUS_SUCCESS';
export const FETCH_GIVEORDERSTATUS_FAILURE = 'FETCH_GIVEORDERSTATUS_FAILURE';
// get orderStatus
export const FETCH_VIEWORDERSTATUS_REQUEST = 'FETCH_VIEWORDERSTATUS_REQUEST';
export const FETCH_VIEWORDERSTATUS_SUCCESS = 'FETCH_VIEWORDERSTATUS_SUCCESS';
export const FETCH_VIEWORDERSTATUS_FAILURE = 'FETCH_VIEWORDERSTATUS_FAILURE';
