export const FETCH_HALLSEARCH_REQUEST = 'FETCH_HALLSEARCHS_REQUEST';
export const FETCH_HALLSEARCH_SUCCESS = 'FETCH_HALLSEARCH_SUCCESS';
export const FETCH_HALLSEARCH_FAILURE = 'FETCH_HALLSEARCH_FAILURE';
export const SET_SELECTED_DEALER = 'SET_SELECTED_DEALER';
export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';
export const SET_SELECTED_EMAIL = 'SET_SELECTED_EMAIL';
