export const FETCH_HALLSEARCH_REQUEST = 'FETCH_HALLSEARCHS_REQUEST';
export const FETCH_HALLSEARCH_SUCCESS = 'FETCH_HALLSEARCH_SUCCESS';
export const FETCH_HALLSEARCH_FAILURE = 'FETCH_HALLSEARCH_FAILURE';
