export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// DElETE user
export const FETCH_DELETE_REQUEST = 'FETCH_DELETE_REQUEST';
export const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS';
export const FETCH_DELETE_FAILURE = 'FETCH_DELETE_FAILURE';

// Update User
export const FETCH_UPDATE_REQUEST = 'FETCH_UPDATE_REQUEST';
export const FETCH_UPDATE_SUCCESS = 'FETCH_UPDATE_SUCCESS';
export const FETCH_UPDATE_FAILURE = 'FETCH_UPDATE_FAILURE';
