export const FETCH_BOOKINGHALL_REQUEST = 'FETCH_BOOKINGHALL_REQUEST';
export const FETCH_BOOKINGHALL_SUCCESS = 'FETCH_BOOKINGHALL_SUCCESS';
export const FETCH_BOOKINGHALL_FAILURE = 'FETCH_BOOKINGHALL_FAILURE';
