export const FETCH_PHOTOGRAPHYORDER_REQUEST = 'FETCH_PHOTOGRAPHYORDER_REQUEST';
export const FETCH_PHOTOGRAPHYORDER_SUCCESS = 'FETCH_PHOTOGRAPHYORDER_SUCCESS';
export const FETCH_PHOTOGRAPHYORDER_FAILURE = 'FETCH_PHOTOGRAPHYORDER_FAILURE';
export const SET_SELECTED_PRICE = 'SET_SELECTED_PRICE';
export const SET_SELECTED_DEALER = 'SET_SELECTED_DEALER';
